#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : forkstat
Version  : 0.03.00
Release  : 1
URL      : https://github.com/ColinIanKing/forkstat/archive/refs/tags/V0.03.00.tar.gz
Source0  : https://github.com/ColinIanKing/forkstat/archive/refs/tags/V0.03.00.tar.gz
Summary  : forkstat is a program that logs process fork(), exec() and exit() activity.
Group    : Development/Tools
License  : GPL-2.0
Requires: forkstat-bin = %{version}-%{release}
Requires: forkstat-data = %{version}-%{release}
Requires: forkstat-license = %{version}-%{release}
Requires: forkstat-man = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Forkstat
Forkstat is a program that logs process fork(), exec() and exit() activity. It is useful for monitoring system behaviour and to track down rogue processes that are spawning off processes and potentially abusing the system.

%package bin
Summary: bin components for the forkstat package.
Group: Binaries
Requires: forkstat-data = %{version}-%{release}
Requires: forkstat-license = %{version}-%{release}

%description bin
bin components for the forkstat package.


%package data
Summary: data components for the forkstat package.
Group: Data

%description data
data components for the forkstat package.


%package license
Summary: license components for the forkstat package.
Group: Default

%description license
license components for the forkstat package.


%package man
Summary: man components for the forkstat package.
Group: Default

%description man
man components for the forkstat package.


%prep
%setup -q -n forkstat-0.03.00
cd %{_builddir}/forkstat-0.03.00

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1675867441
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1675867441
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/forkstat
cp %{_builddir}/forkstat-%{version}/COPYING %{buildroot}/usr/share/package-licenses/forkstat/4cc77b90af91e615a64ae04893fdffa7939db84c || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/forkstat

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/forkstat

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/forkstat/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/forkstat.8.gz
